// Texas Lottery Scratch-Off Games Data
// Last Updated: July 22, 2026 (generated by scripts/update-static-data.js)
// Source: Texas Lottery Official Website

const TEXAS_SCRATCH_OFFS = [
    // $1 Games
    { id: 2710, name: "9s In A Line", price: 1, topPrize: 500, overallOdds: 4.45, topPrizesTotal: 163, topPrizesRemaining: 36, type: "standard" },

    // $2 Games
    { id: 2646, name: "20X The Money", price: 2, topPrize: 30000, overallOdds: 4.95, topPrizesTotal: 5, topPrizesRemaining: 2, type: "multiplier" },
    { id: 2700, name: "Break the Bank", price: 2, topPrize: 30000, overallOdds: 4.8, topPrizesTotal: 10, topPrizesRemaining: 2, type: "standard" },
    { id: 2647, name: "Cash Line Bingo", price: 2, topPrize: 30000, overallOdds: 4.09, topPrizesTotal: 10, topPrizesRemaining: 5, type: "bingo" },
    { id: 2656, name: "Crazy 8s", price: 2, topPrize: 30000, overallOdds: 3.99, topPrizesTotal: 6, topPrizesRemaining: 2, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2715, name: "Find $200", price: 2, topPrize: 200, overallOdds: 4.82, topPrizesTotal: 7609, topPrizesRemaining: 5093, type: "standard" },
    { id: 2739, name: "King of Cash", price: 2, topPrize: 30000, overallOdds: 4.87, topPrizesTotal: 5, topPrizesRemaining: 3, type: "standard" },
    { id: 2622, name: "Lucky No. 7", price: 2, topPrize: 30000, overallOdds: 4.33, topPrizesTotal: 6, topPrizesRemaining: 4, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2692, name: "Patriotic Payout", price: 2, topPrize: 30000, overallOdds: 4.03, topPrizesTotal: 5, topPrizesRemaining: 3, type: "standard", salesStatus: "pulled", endDate: "2026-08-12T05:00:00.000Z" },
    { id: 2672, name: "Royal Riches", price: 2, topPrize: 30000, overallOdds: 4.4, topPrizesTotal: 5, topPrizesRemaining: 2, type: "standard" },

    // $3 Games
    { id: 2711, name: "30X The Cash Word Search", price: 3, topPrize: 60000, overallOdds: 4.39, topPrizesTotal: 6, topPrizesRemaining: 4, type: "crossword" },
    { id: 2662, name: "Cashword", price: 3, topPrize: 50000, overallOdds: 4.07, topPrizesTotal: 13, topPrizesRemaining: 9, type: "crossword" },
    { id: 2628, name: "Texas Loteria", price: 3, topPrize: 50000, overallOdds: 4.38, topPrizesTotal: 14, topPrizesRemaining: 5, type: "loteria" },

    // $5 Games
    { id: 2577, name: "$100,000 Cash", price: 5, topPrize: 100000, overallOdds: 4.07, topPrizesTotal: 5, topPrizesRemaining: 4, type: "standard" },
    { id: 2712, name: "50X The Cash", price: 5, topPrize: 200000, overallOdds: 4.13, topPrizesTotal: 4, topPrizesRemaining: 2, type: "multiplier" },
    { id: 2745, name: "Airstream® Dream", price: 5, topPrize: 100000, overallOdds: 4.28, topPrizesTotal: 5, topPrizesRemaining: 4, type: "standard" },
    { id: 2727, name: "All About the 8s", price: 5, topPrize: 100000, overallOdds: 4.28, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2751, name: "Azulejos", price: 5, topPrize: 100000, overallOdds: 4.15, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2667, name: "Bingo Times 20", price: 5, topPrize: 100000, overallOdds: 4.26, topPrizesTotal: 5, topPrizesRemaining: 2, type: "bingo" },
    { id: 2430, name: "Bonus Break the Bank", price: 5, topPrize: 100000, overallOdds: 4.28, topPrizesTotal: 10, topPrizesRemaining: 5, type: "standard" },
    { id: 2720, name: "Chameleon Cash", price: 5, topPrize: 100000, overallOdds: 4.18, topPrizesTotal: 5, topPrizesRemaining: 1, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2683, name: "Emerald 7s", price: 5, topPrize: 200000, overallOdds: 4.23, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2660, name: "In the Green", price: 5, topPrize: 100000, overallOdds: 4.34, topPrizesTotal: 6, topPrizesRemaining: 1, type: "standard" },
    { id: 2765, name: "Loteria Azul", price: 5, topPrize: 100000, overallOdds: 3.83, topPrizesTotal: 5, topPrizesRemaining: 3, type: "loteria" },
    { id: 2723, name: "Lucky 7s Tripler", price: 5, topPrize: 100000, overallOdds: 4.26, topPrizesTotal: 4, topPrizesRemaining: 0, type: "standard", salesStatus: "pulled", endDate: "2026-08-07T05:00:00.000Z" },
    { id: 2736, name: "Monaco Cash", price: 5, topPrize: 200000, overallOdds: 4.3, topPrizesTotal: 5, topPrizesRemaining: 2, type: "standard" },
    { id: 2747, name: "Ms.PAC-MAN", price: 5, topPrize: 100000, overallOdds: 4.05, topPrizesTotal: 5, topPrizesRemaining: 5, type: "standard" },
    { id: 2740, name: "Super Crossword", price: 5, topPrize: 100000, overallOdds: 4.07, topPrizesTotal: 10, topPrizesRemaining: 9, type: "crossword" },
    { id: 2648, name: "Super Loteria", price: 5, topPrize: 100000, overallOdds: 3.77, topPrizesTotal: 30, topPrizesRemaining: 6, type: "loteria" },
    { id: 2743, name: "Super Loteria", price: 5, topPrize: 100000, overallOdds: 3.77, topPrizesTotal: 30, topPrizesRemaining: 29, type: "loteria" },
    { id: 2728, name: "Yellowstone", price: 5, topPrize: 100000, overallOdds: 4.26, topPrizesTotal: 5, topPrizesRemaining: 3, type: "standard" },

    // $10 Games
    { id: 2636, name: "$1,000,000 Riches", price: 10, topPrize: 1000000, overallOdds: 3.82, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2668, name: "$250,000 50X Cashword", price: 10, topPrize: 250000, overallOdds: 3.56, topPrizesTotal: 10, topPrizesRemaining: 6, type: "crossword" },
    { id: 2637, name: "$50, $100 OR $500!", price: 10, topPrize: 500, overallOdds: 9.43, topPrizesTotal: 10081, topPrizesRemaining: 2620, type: "standard", salesStatus: "pulled", endDate: "2026-09-02T05:00:00.000Z" },
    { id: 2691, name: "100X Sonic Blast", price: 10, topPrize: 250000, overallOdds: 3.67, topPrizesTotal: 4, topPrizesRemaining: 1, type: "multiplier", salesStatus: "pulled", endDate: "2026-08-12T05:00:00.000Z" },
    { id: 2713, name: "100X The Cash", price: 10, topPrize: 500000, overallOdds: 3.98, topPrizesTotal: 4, topPrizesRemaining: 2, type: "multiplier" },
    { id: 2632, name: "777", price: 10, topPrize: 250000, overallOdds: 3.22, topPrizesTotal: 8, topPrizesRemaining: 3, type: "standard" },
    { id: 2676, name: "Limited Edition Mega Loteria", price: 10, topPrize: 250000, overallOdds: 3.54, topPrizesTotal: 10, topPrizesRemaining: 3, type: "loteria" },
    { id: 2705, name: "Lucky Match", price: 10, topPrize: 250000, overallOdds: 3.62, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2733, name: "Mega Cash!", price: 10, topPrize: 250000, overallOdds: 3.89, topPrizesTotal: 5, topPrizesRemaining: 4, type: "standard" },
    { id: 2669, name: "Mega Loteria", price: 10, topPrize: 250000, overallOdds: 3.54, topPrizesTotal: 10, topPrizesRemaining: 3, type: "loteria" },
    { id: 2737, name: "Monaco VIP", price: 10, topPrize: 500000, overallOdds: 4.09, topPrizesTotal: 4, topPrizesRemaining: 3, type: "standard" },
    { id: 2699, name: "Reindeer Riches", price: 10, topPrize: 250000, overallOdds: 3.75, topPrizesTotal: 5, topPrizesRemaining: 1, type: "standard", salesStatus: "pulled", endDate: "2026-08-12T05:00:00.000Z" },
    { id: 2724, name: "Slots of Luck", price: 10, topPrize: 250000, overallOdds: 3.82, topPrizesTotal: 6, topPrizesRemaining: 4, type: "standard" },

    // $20 Games
    { id: 2744, name: "$1,000,000 Ca$h!", price: 20, topPrize: 1000000, overallOdds: 3.99, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2753, name: "$1,000,000 Crossword", price: 20, topPrize: 1000000, overallOdds: 3.41, topPrizesTotal: 6, topPrizesRemaining: 6, type: "crossword" },
    { id: 2658, name: "$1,000,000 CROSSWORD", price: 20, topPrize: 1000000, overallOdds: 3.41, topPrizesTotal: 6, topPrizesRemaining: 1, type: "crossword" },
    { id: 2609, name: "$100, $200, $500 OR $1,000!", price: 20, topPrize: 1000, overallOdds: 9.49, topPrizesTotal: 4913, topPrizesRemaining: 1341, type: "standard", salesStatus: "pulled", endDate: "2026-09-02T05:00:00.000Z" },
    { id: 2613, name: "200X The Cash", price: 20, topPrize: 1000000, overallOdds: 3.41, topPrizesTotal: 4, topPrizesRemaining: 3, type: "multiplier" },
    { id: 2714, name: "200X The Cash", price: 20, topPrize: 1000000, overallOdds: 3.88, topPrizesTotal: 4, topPrizesRemaining: 2, type: "multiplier" },
    { id: 2685, name: "Diamond 7s", price: 20, topPrize: 1000000, overallOdds: 3.51, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2655, name: "Extreme Multiplier", price: 20, topPrize: 1000000, overallOdds: 3.75, topPrizesTotal: 4, topPrizesRemaining: 1, type: "multiplier" },
    { id: 2671, name: "Instant Millions", price: 20, topPrize: 1000000, overallOdds: 3.8, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2722, name: "Mega Millionaire", price: 20, topPrize: 1000000, overallOdds: 3.84, topPrizesTotal: 4, topPrizesRemaining: 3, type: "standard" },
    { id: 2653, name: "Million Dollar Loteria", price: 20, topPrize: 1000000, overallOdds: 3.29, topPrizesTotal: 10, topPrizesRemaining: 2, type: "loteria" },
    { id: 2738, name: "Monaco Millionaire", price: 20, topPrize: 1000000, overallOdds: 3.74, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2725, name: "Power 20s", price: 20, topPrize: 1000000, overallOdds: 3.61, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2706, name: "Queen of Spades", price: 20, topPrize: 1000000, overallOdds: 3.88, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },

    // $30 Games
    { id: 2730, name: "Millionaire's Club", price: 30, topPrize: 2000000, overallOdds: 3.54, topPrizesTotal: 4, topPrizesRemaining: 3, type: "standard" },
    { id: 2661, name: "Premier Play", price: 30, topPrize: 1000000, overallOdds: 3.55, topPrizesTotal: 10, topPrizesRemaining: 5, type: "standard" },

    // $50 Games
    { id: 2624, name: "$5 Million Royale", price: 50, topPrize: 5000000, overallOdds: 3.66, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2589, name: "500X", price: 50, topPrize: 1000000, overallOdds: 3.36, topPrizesTotal: 15, topPrizesRemaining: 2, type: "multiplier", salesStatus: "closing", endDate: "2026-09-16T05:00:00.000Z" },
    { id: 2659, name: "500X Loteria Spectacular", price: 50, topPrize: 3000000, overallOdds: 3.21, topPrizesTotal: 4, topPrizesRemaining: 2, type: "loteria" },
    { id: 2689, name: "Casino Millions", price: 50, topPrize: 1000000, overallOdds: 3.45, topPrizesTotal: 10, topPrizesRemaining: 8, type: "themed" },
    { id: 2677, name: "Golden Riches", price: 50, topPrize: 2000000, overallOdds: 3.76, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2610, name: "Ultimate Millions", price: 50, topPrize: 1000000, overallOdds: 3.59, topPrizesTotal: 4, topPrizesRemaining: 3, type: "standard" },
    { id: 2590, name: "X", price: 50, topPrize: 1000000, overallOdds: 3.49, topPrizesTotal: 4, topPrizesRemaining: 1, type: "standard", salesStatus: "closing", endDate: "2026-09-30T05:00:00.000Z" },

    // $100 Games
    { id: 2400, name: "$20 Million Supreme", price: 100, topPrize: 20000000, overallOdds: 3.49, topPrizesTotal: 4, topPrizesRemaining: 0, type: "standard", salesStatus: "pulled", endDate: "2026-08-21T05:00:00.000Z" },
    { id: 2627, name: "$5 Million Titanium Black", price: 100, topPrize: 5000000, overallOdds: 3.89, topPrizesTotal: 4, topPrizesRemaining: 3, type: "standard" },
    { id: 2665, name: "$5,000,000 Fortune", price: 100, topPrize: 5000000, overallOdds: 3.91, topPrizesTotal: 4, topPrizesRemaining: 2, type: "standard" },
    { id: 2587, name: "Loteria Supreme", price: 100, topPrize: 7500000, overallOdds: 3.23, topPrizesTotal: 4, topPrizesRemaining: 2, type: "loteria" }
];

// Prize breakdown data for detailed view
const PRIZE_BREAKDOWNS = {
    2621: [ // $1,000,000 Blitz
        { prize: 1000000, total: 6, remaining: 3, odds: "1:2,000,000" },
        { prize: 10000, total: 40, remaining: 22, odds: "1:300,000" },
        { prize: 1000, total: 500, remaining: 285, odds: "1:24,000" },
        { prize: 500, total: 1200, remaining: 720, odds: "1:10,000" },
        { prize: 100, total: 15000, remaining: 9200, odds: "1:800" },
        { prize: 50, total: 40000, remaining: 26000, odds: "1:300" },
        { prize: 20, total: 120000, remaining: 82000, odds: "1:100" }
    ],
    2400: [ // $20 Million Supreme
        { prize: 20000000, total: 2, remaining: 2, odds: "1:3,024,000" },
        { prize: 1000000, total: 8, remaining: 5, odds: "1:756,000" },
        { prize: 100000, total: 24, remaining: 16, odds: "1:252,000" },
        { prize: 10000, total: 100, remaining: 68, odds: "1:60,480" },
        { prize: 5000, total: 200, remaining: 142, odds: "1:30,240" },
        { prize: 1000, total: 1000, remaining: 720, odds: "1:6,048" },
        { prize: 500, total: 3000, remaining: 2180, odds: "1:2,016" },
        { prize: 200, total: 10000, remaining: 7500, odds: "1:604" },
        { prize: 100, total: 50000, remaining: 38000, odds: "1:120" }
    ]
};

// Texas cities for location search
const TEXAS_CITIES = [
    "Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi",
    "Plano", "Laredo", "Lubbock", "Garland", "Irving", "Amarillo", "Grand Prairie", "Brownsville",
    "McKinney", "Frisco", "Pasadena", "Mesquite", "Killeen", "McAllen", "Waco", "Carrollton",
    "Midland", "Beaumont", "Denton", "Abilene", "Odessa", "Round Rock", "Richardson", "Tyler",
    "Lewisville", "College Station", "Pearland", "San Angelo", "Allen", "League City", "Sugar Land",
    "Edinburg", "Mission", "Longview", "Bryan", "Pharr", "Baytown", "Missouri City", "Temple"
];
